### PR TITLE
Update GlfwOcctWindow.cpp

### PR DESCRIPTION
**Pull request by grotius-cnc**
repair cmake compile error.

### CODE REVIEW

**Comment by mahaidong** [comment]
Cool

**Comment by grotius-cnc** [comment]
Yeah. Nice work.

Maybe you can take a look here, where your example is used :
https://github.com/grotius-cnc/XCreator/tree/main/XOpenCascadeDialog

I am trying to combine a XButton widget with your Occt viewer widget.
It's a working example with a tiny problem.

I don't know how to solve the glfw rendering order, to combine the button with the occt flush.
Maybe you have a idea?? Thanks.

**Comment by mahaidong** [comment]
I find you also using glfw3 in this example?
https://github.com/grotius-cnc/XCreator/tree/main/XDrawOpenGLPrimitives


I will have a look on your opencascade example.

**Comment by grotius-cnc** [comment]
Thank you. I have hope you can fix this. Have seen more of your code. 

I just spent a few hours more. No luck so far..

Yes that XDrawOpenGLPrimitives is a example based on a Glfw3 window. It can be used to make
cad program's or display drawings. 
So far as i can validate, it uses a modern opengl implementation.
Then the primitives,  line, arc, spline etc. Are drawed using triangles, using opengl shader language.

**Pull request merged**
